### ISSUE TITLE
Infected isn't informed about the Jester.

### ISSUE THREAD

**Issue by AaronMcKenney** [Alf21/ttt2-role_inf#13]
I have an issue with how Jester Win State 1 (Jester wins if he is killled) is currently implemented. From my own experiments (set ttt2_jes_winstate to 1, spawn multiple bots, force a bot to be a jester, force myself to be traitor/serialkiller/jackal/infected, and look at the jester bot), I see that that traitor, serialkiller, and jackal are all informed of who the jester is (via their role showing up when the cross-hair hovers over their body), but the infected isn't. I'm not sure why this is, but I think it's a bug.

I believe that the core problem here is that all roles of the type "kill/convert everyone who doesn't share your role" should have a clear indication of who the jester is. It's fine if these roles can kill the jester and trigger their win condition, but the purpose of the jester should be to prevent the Innocent Team from RDM-ing. The four roles I mention should have some form of streamlined notice (preferred) or exemption from this, as they explicitly RDM by design.

Right now, playing with both ttt2_jes_winstate == 1 and infected enabled is extremely unbalanced, because this edge case happens with surprising regularity (due to the infected's desire to spread like wildfire), and the infected are penalized seemingly by random chance. Explicitly, I believe the only way that the infected can currently win in this scenario is if the jester is either far away from everyone else, or is otherwise incapacitated before they are spotted by the infected.

**Comment by TimGoll** [comment]
we changed the baviour is the recent update, so this should work now.
