### ISSUE TITLE
Modify roles table of rolesetup addon

### ISSUE THREAD

**Issue by Blaubeeree** [Alf21/ttt2-role_inf#4]
Please add
`if SERVER then
	-- modify roles table of rolesetup addon
	hook.Add("TTTAModifyRolesTable", "ModifyRoleInfToInno", function(rolesTable)
		local infected = rolesTable[ROLE_INFECTED]

		if not infected then return end

		rolesTable[ROLE_INNOCENT] = rolesTable[ROLE_INNOCENT] + infected
		rolesTable[ROLE_INFECTED] = 0
	end)
end`
that you don't see if there is an infected if you are using the rolesetup addon

**Comment by Alf21** [comment]
This is automatically improved in the next update (this weekend). But ty anyway!
