### ISSUE TITLE
Leaping ability on the infected minion knife weapon

### ISSUE THREAD

**Issue by mikeysaurus** [Alf21/ttt2-role_inf#5]
The TTT1 Version of the infected from the [Town of Terror](https://steamcommunity.com/sharedfiles/filedetails/?id=1092556189) has the infected use a weapon called "claws". The left click is an attack like the knife, and the right click is a leaping ability. You can see it in action at this timestamp [here](https://youtu.be/lQtqUgX4nJA?t=1195) in this video, or alternatively you can imagine the Half-Life 2 Fast-zombie's leap on a right click.

I would try to use the code that Town of Terror uses and merge with the Knife in this mod, however there is no source available as far as I can tell.

**Comment by TimGoll** [comment]
We use hands since quite a while, so I think this one can be closed
